# Generated by Django 5.1.3 on 2024-11-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='balance_after_transiction',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
