# Generated by Django 5.1.3 on 2024-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='borrow_book',
        ),
        migrations.AddField(
            model_name='book',
            name='borrow_book',
            field=models.BooleanField(default=False),
        ),
    ]
